### ISSUE TITLE
Default keepInventory (of this mod) is set to False and cannot be configured

### ISSUE THREAD

**Issue by Neulooo** [rosecat-dev/IndividualKeepInv#1]
I wouldn't want for players on my server to figure this out the hard way.

Could there be a command/config option implemented that would let server admins change the default keepInventory toggle of this mod? Or maybe if it even simply followed the Minecraft's gamerule

**Comment by rosecat-dev** [comment]
Should be added and fully functional now in 1.0.1. Do tell me how it works on your end!

**Comment by Neulooo** [comment]
Does seem to work for new players, not sure about those who previously joined the server but haven't had their keepInventory state changed.

**Comment by Neulooo** [comment]
Thanks for this change, now I'll definitely consider using this mod, however there's one less important nitpick of mine that I'd rather describe in a separate issue.
