### ISSUE TITLE
Update for 1.21?

### ISSUE THREAD

**Issue by Witurtle** [rosecat-dev/IndividualKeepInv#12]
I would like to use this mod for my personal server with friends, but currently it doesn't appear to have a version for Fabric 1.21

**Comment by rosecat-dev** [comment]
Was going to wait for 1.21.1 since we know that's coming, but if I know somebody actively wants 1.21 version, sure! Check back in a day or two.

**Comment by Wuckly** [comment]
I would also like this updated to 1.21 for the same reason as the above person

**Comment by rosecat-dev** [comment]
Updated, check modrinth!
