### ISSUE TITLE
KeepInventory state cannot be self-assigned via "@s" selector by non-op players.

### ISSUE THREAD

**Issue by Neulooo** [rosecat-dev/IndividualKeepInv#4]
It does still work if you simply input your own name, just not with an "@s". And it does work for operators.

**Comment by rosecat-dev** [comment]
Unfortunately this is an issue with Vanilla Minecraft's code, doesn't allow for non-op players to use selectors, for some reason. I might fix this in the future with a small mixin but for now I'm gonna mark this as won't fix. Doesn't feel worth all the hassle of writing a new mixin; they're still pretty intimidating to me.
