### ISSUE TITLE
Crashing when joining server

### ISSUE THREAD

**Issue by douglasdtlltd** [rosecat-dev/IndividualKeepInv#7]
Crashing during player join

[2023-11-05-7.log.gz](https://github.com/rosecat-dev/IndividualKeepInv/files/13262929/2023-11-05-7.log.gz)

![image](https://github.com/rosecat-dev/IndividualKeepInv/assets/25917193/2c3707b3-1465-4347-8bc4-b81efb84d1fd)

**Comment by rosecat-dev** [comment]
You're attempting to run the mod on Minecraft 1.20.2, which the mod currently doesn't support. A 1.20.2 version will be released soon.

**Comment by douglasdtlltd** [comment]
Copy, thanks.
