### ISSUE TITLE
1.20.4 Compatibility?

### ISSUE THREAD

**Issue by Hanhula** [rosecat-dev/IndividualKeepInv#9]
Hey hey! Just wondering - this mod is tagged with 1.20.2, and I'd like to run it on a 1.20.4 server as one of my friends despises KeepInventory and the rest of us want it on. 

D'you think it'd be compatible as-is, or do we need an update to be able to run it? If so, would it be possible to get that update?

Thanks!

**Comment by rosecat-dev** [comment]
Hello, thank you for your interest! I'm not sure if it would work or not on 1.20.4, but I suppose it wouldn't hurt to try.

In any case, I'll see about getting that 1.20.4 update out as soon as I can.
